layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: docs
    web_url: https://github.com/topics/docs
  - name: C#
    web_url: https://github.com/topics/C#
  - name: F#
    web_url: https://github.com/topics/F#
  - name: System Design
    web_url: https://github.com/topics/system-design
  - name: Web
    web_url: https://github.com/topics/web
  - name: Web design
    web_url: https://github.com/topics/web-design
  - name: ASP.NET Core
    web_url: https://github.com/topics/asp-net-core